2025-03-06 00:11:24,900 - prediction_model - INFO - Logging to file: C:\Users\clubs\Desktop\Prediction Model\data\Logs\prediction_model_20250306_001124.log
2025-03-06 00:11:27,133 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:11:31,967 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:11:32,037 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 514, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:12:02,199 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:12:31,844 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:13:25,662 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    title='Correlation Matrix',
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:13:25,714 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 514, in main_dashboard
    csv_data = df_vis.to_csv(index=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:14:38,948 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:14:42,840 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 545, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:14:42,885 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 524, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:18:09,360 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:18:13,148 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 596, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:18:13,192 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 526, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:19:54,285 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:19:58,109 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:21:31,196 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:21:34,910 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 659, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:21:34,955 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 534, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:25:19,338 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:25:24,514 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 659, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:25:24,580 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 534, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:26:53,058 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:27:39,764 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:27:40,584 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:27:41,018 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:27:41,401 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:27:42,671 - prediction_model - ERROR - Critical error in main dashboard: name 'metrics_col1' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 335, in main_dashboard
    with metrics_col1:
NameError: name 'metrics_col1' is not defined
2025-03-06 00:29:04,394 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:29:08,214 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 603, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:29:08,265 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 548, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:37:54,253 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:37:59,035 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 604, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:37:59,098 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 566, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:39:04,635 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:39:08,833 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 604, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:39:08,872 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 566, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:40:10,535 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:40:15,160 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:41:40,920 - prediction_model - ERROR - Critical error in main dashboard: name 'current_trial' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 353, in main_dashboard
    st.progress(min(1.0, current_trial/max(1, total_trials)))
NameError: name 'current_trial' is not defined
2025-03-06 00:41:55,469 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:41:59,358 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 604, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:41:59,419 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 566, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:46:23,687 - prediction_model - ERROR - Critical error in main dashboard: local variable 'current_trial' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 353, in main_dashboard
    st.progress(min(1.0, current_trial/max(1, total_trials)))
UnboundLocalError: local variable 'current_trial' referenced before assignment
2025-03-06 00:46:41,589 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:46:45,351 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 604, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:46:45,385 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 566, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
2025-03-06 00:58:03,335 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-06 00:58:06,815 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 645, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-06 00:58:06,866 - prediction_model - ERROR - Critical error in main dashboard: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 759, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 557, in main_dashboard
    st.dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\dataframe_selector.py", line 116, in dataframe
    return self.dg._arrow_dataframe(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\metrics_util.py", line 311, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 115, in _arrow_dataframe
    marshall(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 191, in marshall
    _marshall_styler(proto, data, default_uuid)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 232, in _marshall_styler
    _marshall_display_values(proto, styler.data, pandas_styles)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\elements\arrow.py", line 416, in _marshall_display_values
    proto.styler.display_values = type_util.data_frame_to_bytes(new_df)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\type_util.py", line 767, in data_frame_to_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow\\table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 626, in convert_column
    raise e
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pyarrow\pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\\array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ('Input object was not a NumPy array', "Conversion failed for column ('date', '') with type object")
