2025-03-05 20:49:41,084 - prediction_model - INFO - Logging to file: c:\Users\clubs\Desktop\Prediction Model\data\Logs\prediction_model_20250305_204941.log
2025-03-05 20:49:41,655 - prediction_model - ERROR - Error in create_metrics_cards: Invalid format specifier
Traceback (most recent call last):
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_error.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_ui.py", line 301, in create_metrics_cards
    st.markdown(f'''
ValueError: Invalid format specifier
2025-03-05 20:49:41,659 - prediction_model - ERROR - Critical error in main dashboard: 'st.session_state has no key "error_log". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
Traceback (most recent call last):
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_error.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_ui.py", line 301, in create_metrics_cards
    st.markdown(f'''
ValueError: Invalid format specifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\session_state.py", line 438, in __getitem__
    return self._getitem(widget_id, key)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\session_state.py", line 482, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 156, in main_dashboard
    create_metrics_cards()
  File "c:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_error.py", line 59, in wrapper
    st.session_state["error_log"].append(
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 93, in __getitem__
    return get_session_state()[key]
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 111, in __getitem__
    return self._state[key]
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\session_state.py", line 440, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "error_log". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
